# Docker compose config to run a container with the required mounts
services:
  exploration_benchmarking:
    image: ros2humble:exploration_benchmarking
    container_name: exploration_bench
    volumes:
      # Bind mounts: current directory -> container
      - .:/root/exploration_benchmarking
    environment:
      - ROS_DOMAIN_ID=42
    working_dir: /root/exploration_benchmarking/ros2_simulation
    stdin_open: true
    tty: true
