rosbag2_recorded_topics: [
    "/odom", # robot odometry
    "/ground_truth", # ground truth robot position
    "/cmd_vel",
    "/rosout", # logs, not really useful
    "/goal_sent", # goals sent by the exploration algorithmFalse
    "/goal_reached", # goals reached by the exploration algorithm
    "/clock", # clock, to use sim time
    "/scan", # Useful for replaying
    "/tf",
    "/tf_static",
    "/robot_distances", # Published by exploration_benchmarking/distance_check.py
    "/closest_obstacle", # Published by exploration_benchmarking/laser_scan_check.py
    "/estimated_pose", # Published by exploration_benchmarking/estimated_pose_publisher.py

    # "-a",
  ]
rosbag2_played_topics: [
    "/odom", # robot odometry
    "/ground_truth", # ground truth robot position
    "/cmd_vel",
    #"/rosout",
    "/goal_sent",
    "/goal_reached",
    "/clock", # clock, to use sim time
    "/scan",
    "/tf",
    "/tf_static",
  ]

rate: 1.0 # Hz, the rate at which the bag is replayed
map_saver_interval: 10 # seconds, wall time
#world_name: "E34-2" # Irrelevant since no simulation is launched
rviz_config: "rviz/explore-lite.rviz" # path to the rviz config file. If empty or if key is deleted, no rviz will be launched.

# Since there is already a map->odom transform in /tf, we need to use a different name for the map frame.
slam:
  package: "slam_toolbox"
  name: "online_async_launch.py"
  is_launch_file: true #
  params_file: "params/slam/slam_toolbox_1.yaml"
  params_file_argument: "slam_params_file" # The name of the argument to pass the params file to the launchfile.
  launchfile_args: # For a launchfile
    use_sim_time: "true"
    autostart: "true"

additional_processes: # List of other nodes or launch files to run. The list containes dicts, with keys "package", "name", ...
  - package: "exploration_benchmarking"
    name: "laser_scan_check"
    is_launch_file: false
    other_params:
      distance_threshold: 0.6
      use_sim_time: "true"
  - package: "exploration_benchmarking"
    name: "distance_check"
    is_launch_file: false
    other_params:
      use_sim_time: "true"
  - package: "exploration_benchmarking"
    name: "nav_stack_listener"
    is_launch_file: false
    other_params:
      use_sim_time: "true"
  - package: "exploration_benchmarking"
    name: "estimated_pose_publisher"
    is_launch_file: false
    other_params:
      use_sim_time: "true"
