rosbag2_recorded_topics: [
        "/odom", # robot odometry
        "/ground_truth", # ground truth robot position
        "/cmd_vel",
        "/rosout", # logs, not really useful
        "/goal_sent", # goals sent by the exploration algorithmFalse
        "/goal_reached", # goals reached by the exploration algorithm
        "/clock", # clock, to use sim time
        "/scan", # Useful for replaying
        "/tf",
        "/tf_static",
        # "-a",
    ]
map_saver_interval: 10 # seconds, wall time. To not save the map during the run, set to 0
world_name: "E34-2" # Replace with the actual world name, without the .world extension.
rviz_config: "rviz/explore-lite.rviz" # path to the rviz config file. If empty or if key is deleted, no rviz will be launched.

slam:
    package: "gmapper" # Package containing the SLAM node /launch file
    name: "gmap" # Can be launch file (ending with .py or .xml) or node name (e.g. "slam_toolbox")
    is_launch_file: false # Set to true if slam_name is a launch file, false if it is a node name.
    params_file: "params/slam/gmapping_1.yaml" # Relative Path to the SLAM parameters file for nodes, from the folder where singlerun.py is. if using a launchfile, the path will be passed on the params_file argument.
    params_file_argument: "" # The name of the argument to pass the params file to the launchfile.
    launchfile_args: {} # For a launchfile
    ros_args: ["--log-level", "info", "--log-level", "rcl:=warn"] # Other arguments to pass to the CLI, without the "--ros-args" prefix.

navigation:
    package: "nav2_bringup"
    name: "navigation_launch.py"
    is_launch_file: true
    params_file: "params/navigation/nav2_params.yaml"
    params_file_argument: "params_file"
    launchfile_args:
        use_sim_time: "true"
        autostart: "true"
        log_level: "info"
    ros_args: []

exploration:
    package: "explore_lite"
    name: "explore"
    is_launch_file: false
    params_file: "params/exploration/params.yaml"
    params_file_argument: "" # Not used for a node
    # other_params maybe i could put the use sim time here
    launchfile_args: {}
    ros_args: ["--log-level", "info", "--log-level", "rcl:=warn"]

simulation:
    package: "stage_ros2"
    name: "stage.launch.py"
    is_launch_file: true
    params_file: ""
    params_file_argument: "" # Not used here
    launchfile_args:
        enforce_prefixes: "false"
        use_static_transformations: "true"
        one_tf_tree: "false"
    ros_args: []

additional_processes: [] # List of other nodes or launch files to run. The list containes dicts, with keys "package", "name", ...
